### ISSUE TITLE
Custom policies

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/mcp-catalog-operator#3]
- I want to configure in the `McpServer` CRD the configuration of custom policies to define what RBAC Roles are required to execute specific tools.
- Tools not associated to any policy are not restricted to any permission role.

Example of Policy in the `McpServer` manifest:
```yaml
spec:
    auth:
        enabled: true
        policies:
            - tool1:
                - role1
                - role2
            -  tool2:
                - role2
                - role3
```
